fn main() {
    // Force this script to rerun on EVERY build: the RTC seed timestamp
    // (BUILD_SECS_2000) must be fresh, and cargo otherwise caches build-script
    // output until an input changes (observed: a watch seeded 53 min late from
    // a stale stamp). The missing path is always treated as dirty.
    println!("cargo:rerun-if-changed=__force_rerun_for_build_time__");

    generate_sin_lut();
    generate_inter_font();
    generate_bezel_schedules();
    generate_build_time();
    generate_gallery_assets();
    generate_wheel_assets();
    linker_be_nice();
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

/// App Wheel v1 rows (docs/M6-APPWHEEL-PLAN.md §7): name + Lucide icon file.
/// Single source of truth for the font subset, the icon pipeline, and the
/// runtime app table (emitted into wheel_assets.rs).
const WHEEL_APPS: [(&str, &str); 10] = [
    ("Time", "clock"),
    ("Gallery", "image"),
    ("Phone", "phone"),
    ("Messages", "message-circle"),
    ("Activity", "activity"),
    ("Settings", "settings"),
    ("Music", "music"),
    ("Photos", "images"),
    ("Weather", "cloud-sun"),
    ("Timer", "timer"),
];

/// Month names — single source of truth for the font glyph subset AND the
/// runtime date formatter (emitted into the generated font file as MONTH_NAMES).
const MONTHS: [&str; 12] = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
];
/// Ordinal suffix letters ("1st 2nd 3rd 4th").
const ORDINAL_CHARS: &str = "stndrdth";

/// Flash-time RTC seeding (docs/ROADMAP.md M1): embed the host's LOCAL wall
/// clock at build time as seconds since 2000-01-01 00:00:00 (local). The
/// firmware seeds the PCF85063 only when its VL flag is set or it reads a
/// time earlier than this constant — so the RTC keeps time across reflashes.
fn generate_build_time() {
    use std::time::{SystemTime, UNIX_EPOCH};
    let utc_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock")
        .as_secs() as i64;
    let local_offset_secs = local_utc_offset_secs();
    // Unix epoch (1970-01-01) → 2000-01-01 is 10957 days.
    let secs_2000_local = utc_secs + local_offset_secs - 10_957 * 86_400;
    assert!(secs_2000_local > 0, "host clock before year 2000?");

    let git = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    let body = format!(
        "/// Auto-generated by build.rs. Host LOCAL time at build, seconds since 2000-01-01 00:00 local.\n\
         pub const BUILD_SECS_2000: u32 = {secs_2000_local};\n\
         /// Short git hash at build (Settings → About).\n\
         pub const FW_GIT: &str = {git:?};\n"
    );
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("build_time.rs");
    std::fs::write(path, body).expect("write build_time.rs");
    // Deliberately NOT rerun-if-changed on anything extra: cargo reruns build.rs
    // whenever inputs change; the timestamp refreshes on every actual rebuild,
    // which is exactly the "seeded at flash" behavior we want.
}

/// Host local-UTC offset in seconds. Rust std has no timezone API, so ask the
/// OS once at build time (Windows dev host → PowerShell). Falls back to UTC.
fn local_utc_offset_secs() -> i64 {
    let out = std::process::Command::new("powershell")
        .args([
            "-NoProfile",
            "-Command",
            "[int]([TimeZoneInfo]::Local.GetUtcOffset([DateTime]::UtcNow).TotalSeconds)",
        ])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .trim()
            .parse()
            .unwrap_or(0),
        _ => 0, // fall back to UTC if the query fails
    }
}

/// Gallery pages (W3 §4.2): page 1 is the Spike artwork (moved from the
/// retired Unlocked scene); pages 2..N auto-ingest from assets/gallery/*
/// — any resolution, center-cropped, resized to the panel, Bayer-dithered
/// to display-ready RGB565-BE. Dropping a file in is all it takes. A file
/// whose name contains "space-cowboy" is the designated finale and always
/// sorts last (it carries the caption).
fn generate_gallery_assets() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    println!("cargo:rerun-if-changed=assets/Spike.jpg");
    println!("cargo:rerun-if-changed=assets/gallery");

    let mut sources: Vec<std::path::PathBuf> = Vec::new();
    let spike = std::path::PathBuf::from("assets/Spike.jpg");
    if spike.exists() {
        sources.push(spike);
    }
    let mut extra: Vec<std::path::PathBuf> = Vec::new();
    if let Ok(rd) = std::fs::read_dir("assets/gallery") {
        for e in rd.flatten() {
            let p = e.path();
            let ext = p
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e.to_ascii_lowercase());
            if matches!(ext.as_deref(), Some("jpg" | "jpeg" | "png")) {
                println!("cargo:rerun-if-changed={}", p.display());
                extra.push(p);
            }
        }
    }
    extra.sort();
    let is_finale = |p: &std::path::Path| {
        p.file_stem()
            .and_then(|s| s.to_str())
            .is_some_and(|s| s.to_ascii_lowercase().contains("space-cowboy"))
    };
    let (rest, finale): (Vec<_>, Vec<_>) = extra.into_iter().partition(|p| !is_finale(p));
    sources.extend(rest);
    sources.extend(finale);
    assert!(!sources.is_empty(), "gallery needs at least one image");

    let mut body = String::from(
        "/// Auto-generated by build.rs (generate_gallery_assets). Do not edit.\n",
    );
    body.push_str(&format!("pub const GALLERY_PAGES: usize = {};\n", sources.len()));
    body.push_str(&format!("pub static GALLERY_ART: [&[u8]; {}] = [\n", sources.len()));
    for (i, src) in sources.iter().enumerate() {
        let out_path = std::path::Path::new(&out_dir).join(format!("gallery_{i}.bin"));
        ingest_to_rgb565(src, &out_path);
        body.push_str(&format!(
            "    include_bytes!(r\"{}\"),\n",
            out_path.display()
        ));
    }
    body.push_str("];\n");
    let path = std::path::Path::new(&out_dir).join("gallery_assets.rs");
    std::fs::write(&path, body).expect("write gallery_assets.rs");
}

/// Decode → center-crop square → resize 466×466 → Bayer-4×4 dither →
/// RGB565 big-endian raw binary (display-ready; blitting is one memcpy).
/// Skips the expensive pipeline when the output is already fresh.
fn ingest_to_rgb565(src_path: &std::path::Path, out_path: &std::path::Path) {
    const W: u32 = 466;
    const H: u32 = 466;
    const BAYER: [[i32; 4]; 4] = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]];

    if let (Ok(out_meta), Ok(src_meta), Ok(script_meta)) = (
        std::fs::metadata(out_path),
        std::fs::metadata(src_path),
        std::fs::metadata("build.rs"),
    ) {
        if let (Ok(out_t), Ok(src_t), Ok(script_t)) = (
            out_meta.modified(),
            src_meta.modified(),
            script_meta.modified(),
        ) {
            if out_t > src_t && out_t > script_t {
                return;
            }
        }
    }

    let img = image::open(src_path)
        .unwrap_or_else(|e| panic!("decode {}: {e}", src_path.display()))
        .to_rgb8();
    let (iw, ih) = (img.width(), img.height());
    let side = iw.min(ih);
    let cropped = image::imageops::crop_imm(&img, (iw - side) / 2, (ih - side) / 2, side, side)
        .to_image();
    let resized = image::imageops::resize(&cropped, W, H, image::imageops::FilterType::Lanczos3);

    let mut out = Vec::with_capacity((W * H * 2) as usize);
    for y in 0..H {
        for x in 0..W {
            let p = resized.get_pixel(x, y);
            let d = BAYER[(y % 4) as usize][(x % 4) as usize];
            // Dither amplitude = one quantization step (8 for 5-bit, 4 for 6-bit).
            let r = ((p[0] as i32 + (d - 8) * 8 / 16).clamp(0, 255) >> 3) as u16;
            let g = ((p[1] as i32 + (d - 8) * 4 / 16).clamp(0, 255) >> 2) as u16;
            let b = ((p[2] as i32 + (d - 8) * 8 / 16).clamp(0, 255) >> 3) as u16;
            let px = (r << 11) | (g << 5) | b;
            out.push((px >> 8) as u8);
            out.push(px as u8);
        }
    }
    std::fs::write(out_path, out)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

/// 512-entry Q14 sine LUT for src/trig.rs.
fn generate_sin_lut() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let mut body = String::from("pub static SIN_LUT_I16: [i16; 512] = [\n");
    for i in 0..512 {
        let angle = (i as f64 / 512.0) * std::f64::consts::TAU;
        let q14 = ((angle.sin() * 16384.0).round() as i32).clamp(-32768, 32767);
        body.push_str(&format!("{q14}_i16,\n"));
    }
    body.push_str("];\n");
    let path = std::path::Path::new(&out_dir).join("sin_lut.rs");
    std::fs::write(path, body).expect("write sin_lut.rs");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Per-phase cubic Bezier control points, CSS `cubic-bezier(x1, y1, x2, y2)`
/// semantics (P2, docs/09). Peak per-frame delta ≈ avg × curve's max slope —
/// keep max slope ≤ ~1.6 so the worst anim frame stays inside the 91 ms cadence.
///
/// Startup sweep: pronounced cubic ease — patient wind-up, swift middle, long
/// graceful landing (2026-07-21: deepened from (0.25,0.1,0.75,0.9) which read
/// nearly linear; max slope ~1.8 — budget-checked against the faster stamps).
const INITIAL_BEZIER: (f64, f64, f64, f64) = (0.45, 0.0, 0.25, 1.0);
/// Minute change: snappier still — quick reaction to the tick, soft landing.
const MINUTE_BEZIER: (f64, f64, f64, f64) = (0.4, 0.0, 0.2, 1.0);

/// Bezel ring animation schedules (docs/09 P0): cumulative arc-center counts per frame.
///
/// Frame-indexed, not wall-clock: the runtime applies `schedule[frame_in_phase]` each
/// frame, so per-frame deltas are bounded by construction (no runtime cap needed) and
/// the ring always reaches the schedule's end state before the phase can exit.
fn generate_bezel_schedules() {
    // Must equal the lock-scene precompute size: BEZEL_STEPS (36000) × TAPS (11).
    // scale_sched in lock.rs tolerates a mismatch, but identity keeps per-frame
    // deltas exactly as constructed.
    const TOTAL: u32 = 396_000;
    // The app paces bezel-animation frames at this rate (CLOCK_ANIM_FRAME_US in
    // app.rs), dropping to 20 fps when static. 40 fps halves each frame's arc
    // delta — the mid-sweep speed peak stays visually continuous instead of
    // stepping. Every anim frame's work must fit 25 ms (stride-2 tip restamp
    // keeps the worst frame inside that).
    const TARGET_FPS: u64 = 40;
    const INITIAL_MS: u64 = 8_000;
    const UNDRAW_MS: u64 = 3_500;
    const REDRAW_MS: u64 = 3_500;

    let frames = |ms: u64| ((ms * TARGET_FPS + 999) / 1000) as usize;

    let initial = ease_schedule(frames(INITIAL_MS), TOTAL, INITIAL_BEZIER);
    let redraw = ease_schedule(frames(REDRAW_MS), TOTAL, MINUTE_BEZIER);
    // Undraw runs the same S-curve in reverse: TOTAL → 0, slow ends / fast middle.
    let undraw: Vec<u32> = ease_schedule(frames(UNDRAW_MS), TOTAL, MINUTE_BEZIER)
        .iter()
        .map(|&c| TOTAL - c)
        .collect();

    let mut body = String::from(
        "/// Auto-generated by build.rs (generate_bezel_schedules). Do not edit.\n\
         /// Cumulative arc-center counts per frame; index with frame_in_phase.\n",
    );
    body.push_str(&format!(
        "pub const BEZEL_SCHED_TOTAL: u32 = {TOTAL};\n"
    ));
    emit_schedule(&mut body, "BEZEL_INITIAL_SCHEDULE", &initial);
    emit_schedule(&mut body, "BEZEL_UNDRAW_SCHEDULE", &undraw);
    emit_schedule(&mut body, "BEZEL_REDRAW_SCHEDULE", &redraw);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("watch_anim.rs");
    std::fs::write(path, body).expect("write watch_anim.rs");
}

fn emit_schedule(body: &mut String, name: &str, vals: &[u32]) {
    body.push_str(&format!("pub static {name}: &[u32] = &[\n"));
    for chunk in vals.chunks(12) {
        body.push_str("    ");
        for v in chunk {
            body.push_str(&format!("{v}, "));
        }
        body.push('\n');
    }
    body.push_str("];\n");
}

/// Monotonic cumulative schedule: frame i → round(ease(i/(N-1)) × total).
fn ease_schedule(frames: usize, total: u32, bez: (f64, f64, f64, f64)) -> Vec<u32> {
    assert!(frames >= 2, "schedule needs at least 2 frames");
    let mut v = Vec::with_capacity(frames);
    let mut prev = 0u32;
    for i in 0..frames {
        let t = i as f64 / (frames - 1) as f64;
        let y = bezier_ease(bez.0, bez.1, bez.2, bez.3, t);
        let c = ((y * total as f64).round() as u32).clamp(prev, total);
        prev = c;
        v.push(c);
    }
    v[0] = 0;
    let last = frames - 1;
    v[last] = total;
    v
}

/// y for a given x on cubic Bezier (0,0)-(p1)-(p2)-(1,1); x solved by bisection
/// (x(u) is monotonic for control x-coords in [0,1]).
fn bezier_ease(p1x: f64, p1y: f64, p2x: f64, p2y: f64, x: f64) -> f64 {
    let eval = |u: f64, a: f64, b: f64| {
        let inv = 1.0 - u;
        3.0 * inv * inv * u * a + 3.0 * inv * u * u * b + u * u * u
    };
    let (mut lo, mut hi) = (0.0f64, 1.0f64);
    for _ in 0..60 {
        let mid = (lo + hi) / 2.0;
        if eval(mid, p1x, p2x) < x {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    eval((lo + hi) / 2.0, p1y, p2y)
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}

fn generate_inter_font() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let font_path = std::path::Path::new("assets/InterDisplay-Bold.ttf");

    let mut body = String::from("/// Auto-generated from InterDisplay-Bold.ttf via fontdue in build.rs\n\n");

    if !font_path.exists() {
        // Stub so builds don't hard-fail before user places the font.
        body.push_str("pub const INTER_FONT_PRESENT: bool = false;\n");
        body.push_str("#[derive(Copy, Clone)]\npub struct Glyph { pub width: u8, pub height: u8, pub advance: u8, pub ymin: i16, pub data: &'static [u8] }\n");
        body.push_str("pub static TIME_GLYPHS: [Option<Glyph>; 128] = [None; 128];\n");
        body.push_str("pub static TEXT_GLYPHS: [Option<Glyph>; 128] = [None; 128];\n");
        let path = std::path::Path::new(&out_dir).join("inter_font.rs");
        std::fs::write(&path, body).expect("write stub inter_font.rs");
        println!("cargo:warning=assets/InterDisplay-Bold.ttf not found. Place your Inter Display Bold .ttf there. Using stub.");
        println!("cargo:rerun-if-changed=assets/InterDisplay-Bold.ttf");
        return;
    }

    let font_data = std::fs::read(font_path).expect("read Inter font");
    let font = fontdue::Font::from_bytes(font_data.as_slice(), fontdue::FontSettings::default())
        .expect("parse Inter font");

    // Glyph subset derived programmatically so it can never drift from what the
    // date formatter can produce: digits, colon, space, every month name letter,
    // and the ordinal suffixes.
    let mut needed: Vec<char> = "0123456789: ".chars().collect();
    for m in MONTHS {
        needed.extend(m.chars());
    }
    needed.extend(ORDINAL_CHARS.chars());
    // App Wheel: label letters not already covered by the months, plus the
    // status line's separator/percent.
    for (name, _) in WHEEL_APPS {
        needed.extend(name.chars());
    }
    needed.extend("|%".chars());
    // W3 app screens: spaced-caps titles + mock content need the full
    // uppercase alphabet, the Gallery caption its ellipsis dots, and the
    // Messages mock its apostrophe.
    needed.extend("ABCDEFGHIJKLMNOPQRSTUVWXYZ.'".chars());
    needed.sort_unstable();
    needed.dedup();

    body.push_str("pub const INTER_FONT_PRESENT: bool = true;\n");
    body.push_str(&format!(
        "/// Month names (shared with the build-time glyph subset).\npub static MONTH_NAMES: [&str; 12] = {MONTHS:?};\n"
    ));
    // Glyphs carry fontdue's native 8-bit edge coverage quantized to 4-bit
    // alpha (16 levels), rasterized at the FINAL rendered pixel size — the
    // runtime blends directly, no scaling, no coverage reconstruction.
    // data: row-major, 2 px/byte, high nibble = left pixel, stride (w+1)/2.
    body.push_str("#[derive(Copy, Clone)]\npub struct Glyph { pub width: u8, pub height: u8, pub advance: u8, pub ymin: i16, pub data: &'static [u8] }\n");

    // Time digits render at 78 px (was: 72 px raster halved then 3× nearest);
    // 108 pt reproduces that final size exactly. Date text renders at half
    // the old raster → 36 pt.
    let time_chars: Vec<char> = "0123456789:".chars().collect();
    emit_glyph_set(&mut body, &font, "TIME_GLYPHS", &time_chars, 108.0);
    emit_glyph_set(&mut body, &font, "TEXT_GLYPHS", &needed, 36.0);
    // App Wheel focused-row labels (~34 px); unfocused rows reuse TEXT_GLYPHS.
    emit_glyph_set(&mut body, &font, "LABELF_GLYPHS", &needed, 48.0);

    let path = std::path::Path::new(&out_dir).join("inter_font.rs");
    std::fs::write(&path, body).expect("write inter_font.rs");
    println!("cargo:rerun-if-changed=assets/InterDisplay-Bold.ttf");
    println!("cargo:rerun-if-changed=build.rs");
}

/// App Wheel assets (docs/M6-APPWHEEL-PLAN.md): Lucide icons rasterized with
/// resvg's true vector AA at both focus sizes (8-bit alpha sprites), the
/// focus glow ring (an iteration of the lightsaber flourish's bloom frame:
/// blade gradient + layered glow, Bayer-dithered, baked as an intensity
/// sprite colored through the saber LUT at runtime), and the app table.
fn generate_wheel_assets() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    const ICON_S: u32 = 40; // unfocused
    const ICON_L: u32 = 48; // focused (sized to leave the glow ring a few px of padding)
    const ICON_H: u32 = 96; // hero (app content elements)
    const ICON_X: u32 = 128; // splash logo (open/close morph loading beat)

    let mut body = String::from(
        "/// Auto-generated by build.rs (generate_wheel_assets). Do not edit.\n\
         /// Icons: row-major 8-bit alpha, width = height = the size constant.\n\n",
    );
    body.push_str(&format!("pub const ICON_S_PX: i32 = {ICON_S};\n"));
    body.push_str(&format!("pub const ICON_L_PX: i32 = {ICON_L};\n"));
    body.push_str(&format!("pub const ICON_H_PX: i32 = {ICON_H};\n"));
    body.push_str(&format!("pub const ICON_X_PX: i32 = {ICON_X};\n"));

    let mut table = String::from("pub static WHEEL_APPS: &[WheelApp] = &[\n");
    for (idx, (name, file)) in WHEEL_APPS.iter().enumerate() {
        let path = format!("assets/icons/{file}.svg");
        let data = std::fs::read(&path).unwrap_or_else(|_| panic!("read {path}"));
        let opt = resvg::usvg::Options::default();
        let tree = resvg::usvg::Tree::from_data(&data, &opt)
            .unwrap_or_else(|e| panic!("parse {path}: {e}"));
        for (tag, px) in [("S", ICON_S), ("L", ICON_L), ("H", ICON_H), ("X", ICON_X)] {
            let scale = px as f32 / tree.size().width();
            let mut pixmap =
                resvg::tiny_skia::Pixmap::new(px, px).expect("pixmap");
            resvg::render(
                &tree,
                resvg::tiny_skia::Transform::from_scale(scale, scale),
                &mut pixmap.as_mut(),
            );
            body.push_str(&format!("static ICON_{idx}_{tag}: &[u8] = &["));
            for (i, p) in pixmap.pixels().iter().enumerate() {
                if i > 0 {
                    body.push(',');
                }
                body.push_str(&format!("{}", p.alpha()));
            }
            body.push_str("];\n");
        }
        table.push_str(&format!(
            "    WheelApp {{ name: {name:?}, icon_s: ICON_{idx}_S, icon_l: ICON_{idx}_L, icon_h: ICON_{idx}_H, icon_x: ICON_{idx}_X }},\n"
        ));
        println!("cargo:rerun-if-changed={path}");
    }
    table.push_str("];\n");
    body.push_str(
        "#[derive(Clone, Copy)]\npub struct WheelApp { pub name: &'static str, pub icon_s: &'static [u8], pub icon_l: &'static [u8], pub icon_h: &'static [u8], pub icon_x: &'static [u8] }\n",
    );
    body.push_str(&table);

    // W3 app-screen sprites: standalone Lucide rasterizations at their
    // design sizes (aperture = Photos hero, sun = Weather, transport
    // glyphs = Music footer, sparkles = the ✨ stand-in for Messages).
    for (name, file, px) in [
        ("APERTURE", "aperture", 96u32),
        ("SUN", "sun", 72),
        ("SPARKLES", "sparkles", 18),
        ("TR_PREV", "skip-back", 36),
        ("TR_PLAY", "play", 36),
        ("TR_NEXT", "skip-forward", 36),
    ] {
        let path = format!("assets/icons/{file}.svg");
        let data = std::fs::read(&path).unwrap_or_else(|_| panic!("read {path}"));
        let opt = resvg::usvg::Options::default();
        let tree = resvg::usvg::Tree::from_data(&data, &opt)
            .unwrap_or_else(|e| panic!("parse {path}: {e}"));
        let scale = px as f32 / tree.size().width();
        let mut pixmap = resvg::tiny_skia::Pixmap::new(px, px).expect("pixmap");
        resvg::render(
            &tree,
            resvg::tiny_skia::Transform::from_scale(scale, scale),
            &mut pixmap.as_mut(),
        );
        body.push_str(&format!("pub const {name}_PX: i32 = {px};\n"));
        body.push_str(&format!("pub static {name}: &[u8] = &["));
        for (i, p) in pixmap.pixels().iter().enumerate() {
            if i > 0 {
                body.push(',');
            }
            body.push_str(&format!("{}", p.alpha()));
        }
        body.push_str("];\n");
        println!("cargo:rerun-if-changed={path}");
    }

    // Focus glow ring: the flourish bloom-frame look shrunk around an icon.
    // Ring radius 34 px, stroke half-width 2.5 px (blade gradient), layered
    // glow both ways (there is room outside here, unlike the bezel).
    const GLOW_SIZE: i32 = 96;
    const GLOW_R: f64 = 34.0;
    const BAYER: [[i32; 4]; 4] = [[-7, 1, -5, 3], [5, -3, 7, -1], [-4, 4, -6, 2], [8, 0, 6, -2]];
    body.push_str(&format!("pub const GLOW_RING_PX: i32 = {GLOW_SIZE};\n"));
    body.push_str("pub static GLOW_RING: &[u8] = &[");
    let c = (GLOW_SIZE as f64 - 1.0) / 2.0;
    for y in 0..GLOW_SIZE {
        for x in 0..GLOW_SIZE {
            let dx = x as f64 - c;
            let dy = y as f64 - c;
            let d = ((dx * dx + dy * dy).sqrt() - GLOW_R).abs();
            let v: f64 = if d <= 2.5 {
                255.0 - d * d * 6.0
            } else {
                // Two-layer quadratic falloff (tight bright + soft veil).
                let x1 = d - 2.5;
                let l = |a: f64, reach: f64| {
                    if x1 >= reach { 0.0 } else { a * (reach - x1) * (reach - x1) / (reach * reach) }
                };
                (l(150.0, 6.0) + l(70.0, 14.0)).min(220.0)
            };
            // Dither ONLY lit pixels — dithering the empty regions turned the
            // sprite's transparent square into near-black speckle that
            // stamped over neighboring icons at blit time.
            let v = if v >= 1.0 {
                ((v as i32) + BAYER[(y & 3) as usize][(x & 3) as usize]).clamp(1, 255)
            } else {
                0
            };
            if !(x == 0 && y == 0) {
                body.push(',');
            }
            body.push_str(&format!("{v}"));
        }
    }
    body.push_str("];\n");

    // Photos hero: soft inner-glow disc r=80 (flourish bloom tech at low
    // amplitude) — a lit rim at r≈76 with a quadratic glow spilling inward
    // over a faint center veil. Intensity sprite, colored through the
    // azure LUT at runtime with a breathing alpha.
    const DISC_SIZE: i32 = 164;
    const DISC_R: f64 = 76.0;
    body.push_str(&format!("pub const PHOTOS_DISC_PX: i32 = {DISC_SIZE};\n"));
    body.push_str("pub static PHOTOS_DISC: &[u8] = &[");
    let dc = (DISC_SIZE as f64 - 1.0) / 2.0;
    for y in 0..DISC_SIZE {
        for x in 0..DISC_SIZE {
            let dx = x as f64 - dc;
            let dy = y as f64 - dc;
            let d = (dx * dx + dy * dy).sqrt();
            let dr = d - DISC_R;
            let l = |a: f64, x1: f64, reach: f64| {
                if x1 <= 0.0 || x1 >= reach { 0.0 } else { a * (reach - x1) * (reach - x1) / (reach * reach) }
            };
            let core = if dr.abs() <= 2.5 { 165.0 - dr * dr * 9.0 } else { 0.0 };
            let inward = if dr < 0.0 { l(115.0, -dr, 42.0) } else { 0.0 };
            let outward = if dr > 0.0 { l(95.0, dr, 9.0) } else { 0.0 };
            let veil = if d < DISC_R { 26.0 * (1.0 - (d / DISC_R) * (d / DISC_R)) } else { 0.0 };
            let v = (core + inward + outward + veil).min(190.0);
            // Same lit-pixels-only dither doctrine as GLOW_RING.
            let v = if v >= 1.0 {
                ((v as i32) + BAYER[(y & 3) as usize][(x & 3) as usize]).clamp(1, 255)
            } else {
                0
            };
            if !(x == 0 && y == 0) {
                body.push(',');
            }
            body.push_str(&format!("{v}"));
        }
    }
    body.push_str("];\n");

    let path = std::path::Path::new(&out_dir).join("wheel_assets.rs");
    std::fs::write(&path, body).expect("write wheel_assets.rs");
}

/// Emit one `[Option<Glyph>; 128]` set rasterized at `px`, 4-bit alpha packed
/// 2 px/byte (high nibble first).
fn emit_glyph_set(body: &mut String, font: &fontdue::Font, name: &str, chars: &[char], px: f32) {
    body.push_str(&format!("pub static {name}: [Option<Glyph>; 128] = [\n"));
    for c in 0u8..128 {
        let ch = c as char;
        if chars.contains(&ch) {
            let (metrics, bitmap) = font.rasterize(ch, px);
            let w = metrics.width;
            let h = metrics.height;
            let adv = metrics.advance_width.round() as i32;
            assert!(
                w < 256 && h < 256 && (0..256).contains(&adv),
                "glyph '{ch}' at {px}px exceeds u8 metrics (w={w} h={h} adv={adv})"
            );
            let ymin = metrics.ymin as i16;

            let stride = (w + 1) / 2;
            let mut packed: Vec<u8> = vec![0; stride * h];
            for y in 0..h {
                for x in 0..w {
                    let a4 = ((bitmap[y * w + x] as u32 * 15 + 127) / 255) as u8;
                    let idx = y * stride + x / 2;
                    if x % 2 == 0 {
                        packed[idx] |= a4 << 4;
                    } else {
                        packed[idx] |= a4;
                    }
                }
            }

            body.push_str(&format!(
                "    Some(Glyph {{ width: {}, height: {}, advance: {}, ymin: {}, data: &[",
                w, h, adv, ymin
            ));
            for (i, b) in packed.iter().enumerate() {
                if i > 0 {
                    body.push(',');
                }
                body.push_str(&format!("{b}"));
            }
            body.push_str("] }),\n");
        } else {
            body.push_str("    None,\n");
        }
    }
    body.push_str("];\n");
}
