fn main() {
    generate_sin_lut();
    generate_inter_font();
    generate_bezel_schedules();
    generate_build_time();
    generate_spike_asset();
    linker_be_nice();
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

/// Month names — single source of truth for the font glyph subset AND the
/// runtime date formatter (emitted into the generated font file as MONTH_NAMES).
const MONTHS: [&str; 12] = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
];
/// Ordinal suffix letters ("1st 2nd 3rd 4th").
const ORDINAL_CHARS: &str = "stndrdth";

/// Flash-time RTC seeding (docs/ROADMAP.md M1): embed the host's LOCAL wall
/// clock at build time as seconds since 2000-01-01 00:00:00 (local). The
/// firmware seeds the PCF85063 only when its VL flag is set or it reads a
/// time earlier than this constant — so the RTC keeps time across reflashes.
fn generate_build_time() {
    use std::time::{SystemTime, UNIX_EPOCH};
    let utc_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock")
        .as_secs() as i64;
    let local_offset_secs = local_utc_offset_secs();
    // Unix epoch (1970-01-01) → 2000-01-01 is 10957 days.
    let secs_2000_local = utc_secs + local_offset_secs - 10_957 * 86_400;
    assert!(secs_2000_local > 0, "host clock before year 2000?");

    let body = format!(
        "/// Auto-generated by build.rs. Host LOCAL time at build, seconds since 2000-01-01 00:00 local.\n\
         pub const BUILD_SECS_2000: u32 = {secs_2000_local};\n"
    );
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("build_time.rs");
    std::fs::write(path, body).expect("write build_time.rs");
    // Deliberately NOT rerun-if-changed on anything extra: cargo reruns build.rs
    // whenever inputs change; the timestamp refreshes on every actual rebuild,
    // which is exactly the "seeded at flash" behavior we want.
}

/// Host local-UTC offset in seconds. Rust std has no timezone API, so ask the
/// OS once at build time (Windows dev host → PowerShell). Falls back to UTC.
fn local_utc_offset_secs() -> i64 {
    let out = std::process::Command::new("powershell")
        .args([
            "-NoProfile",
            "-Command",
            "[int]([TimeZoneInfo]::Local.GetUtcOffset([DateTime]::UtcNow).TotalSeconds)",
        ])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .trim()
            .parse()
            .unwrap_or(0),
        _ => 0, // fall back to UTC if the query fails
    }
}

/// Unlock image (docs/ROADMAP.md M3): decode assets/Spike.jpg at build time,
/// center-crop to square, resize to the panel, Bayer-4×4 dither to RGB565
/// big-endian (display-ready), and emit as a raw binary for include_bytes!.
/// Runtime JPEG decoding was rejected — single fixed asset, 16 MB flash.
fn generate_spike_asset() {
    const W: u32 = 466;
    const H: u32 = 466;
    // Bayer 4×4 ordered-dither matrix (0..16).
    const BAYER: [[i32; 4]; 4] = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]];

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = std::path::Path::new(&out_dir).join("spike_rgb565.bin");
    let src_path = std::path::Path::new("assets/Spike.jpg");
    println!("cargo:rerun-if-changed=assets/Spike.jpg");

    if !src_path.exists() {
        // Stub: black frame so builds don't hard-fail without the asset.
        std::fs::write(&out_path, vec![0u8; (W * H * 2) as usize]).expect("write stub spike");
        println!("cargo:warning=assets/Spike.jpg missing — unlock image is black.");
        return;
    }

    let img = image::open(src_path).expect("decode Spike.jpg").to_rgb8();
    let (iw, ih) = (img.width(), img.height());
    let side = iw.min(ih);
    let cropped = image::imageops::crop_imm(&img, (iw - side) / 2, (ih - side) / 2, side, side)
        .to_image();
    let resized = image::imageops::resize(&cropped, W, H, image::imageops::FilterType::Lanczos3);

    let mut out = Vec::with_capacity((W * H * 2) as usize);
    for y in 0..H {
        for x in 0..W {
            let p = resized.get_pixel(x, y);
            let d = BAYER[(y % 4) as usize][(x % 4) as usize];
            // Dither amplitude = one quantization step (8 for 5-bit, 4 for 6-bit).
            let r = ((p[0] as i32 + (d - 8) * 8 / 16).clamp(0, 255) >> 3) as u16;
            let g = ((p[1] as i32 + (d - 8) * 4 / 16).clamp(0, 255) >> 2) as u16;
            let b = ((p[2] as i32 + (d - 8) * 8 / 16).clamp(0, 255) >> 3) as u16;
            let px = (r << 11) | (g << 5) | b;
            out.push((px >> 8) as u8);
            out.push(px as u8);
        }
    }
    std::fs::write(&out_path, out).expect("write spike_rgb565.bin");
}

/// 512-entry Q14 sine LUT for src/trig.rs.
fn generate_sin_lut() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let mut body = String::from("pub static SIN_LUT_I16: [i16; 512] = [\n");
    for i in 0..512 {
        let angle = (i as f64 / 512.0) * std::f64::consts::TAU;
        let q14 = ((angle.sin() * 16384.0).round() as i32).clamp(-32768, 32767);
        body.push_str(&format!("{q14}_i16,\n"));
    }
    body.push_str("];\n");
    let path = std::path::Path::new(&out_dir).join("sin_lut.rs");
    std::fs::write(path, body).expect("write sin_lut.rs");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Per-phase cubic Bezier control points, CSS `cubic-bezier(x1, y1, x2, y2)`
/// semantics (P2, docs/09). Peak per-frame delta ≈ avg × curve's max slope —
/// keep max slope ≤ ~1.6 so the worst anim frame stays inside the 91 ms cadence.
///
/// Startup sweep: gentle stately S-curve (validated on hardware — "lovely").
const INITIAL_BEZIER: (f64, f64, f64, f64) = (0.25, 0.1, 0.75, 0.9);
/// Minute change: snappier mid (max slope 1.5), still soft at both ends —
/// reads as a responsive reaction to the tick rather than a slow ornament.
const MINUTE_BEZIER: (f64, f64, f64, f64) = (0.33, 0.0, 0.67, 1.0);

/// Bezel ring animation schedules (docs/09 P0): cumulative arc-center counts per frame.
///
/// Frame-indexed, not wall-clock: the runtime applies `schedule[frame_in_phase]` each
/// frame, so per-frame deltas are bounded by construction (no runtime cap needed) and
/// the ring always reaches the schedule's end state before the phase can exit.
fn generate_bezel_schedules() {
    // Must equal src/clock.rs precompute size: BEZEL_STEPS (36000) × thickness taps (11).
    const TOTAL: u32 = 396_000;
    // The main loop paces frames to exactly this rate (CLOCK_FRAME_US in main.rs),
    // so schedules take precisely their designed wall-clock duration. More fps =
    // more, smaller schedule steps over the same duration = smoother motion;
    // every frame's work must fit 1000/fps ms (worst measured ~45 ms at 20 fps).
    const TARGET_FPS: u64 = 20;
    const INITIAL_MS: u64 = 8_000;
    const UNDRAW_MS: u64 = 3_500;
    const REDRAW_MS: u64 = 3_500;

    let frames = |ms: u64| ((ms * TARGET_FPS + 999) / 1000) as usize;

    let initial = ease_schedule(frames(INITIAL_MS), TOTAL, INITIAL_BEZIER);
    let redraw = ease_schedule(frames(REDRAW_MS), TOTAL, MINUTE_BEZIER);
    // Undraw runs the same S-curve in reverse: TOTAL → 0, slow ends / fast middle.
    let undraw: Vec<u32> = ease_schedule(frames(UNDRAW_MS), TOTAL, MINUTE_BEZIER)
        .iter()
        .map(|&c| TOTAL - c)
        .collect();

    let mut body = String::from(
        "/// Auto-generated by build.rs (generate_bezel_schedules). Do not edit.\n\
         /// Cumulative arc-center counts per frame; index with frame_in_phase.\n",
    );
    body.push_str(&format!(
        "pub const BEZEL_SCHED_TOTAL: u32 = {TOTAL};\n"
    ));
    emit_schedule(&mut body, "BEZEL_INITIAL_SCHEDULE", &initial);
    emit_schedule(&mut body, "BEZEL_UNDRAW_SCHEDULE", &undraw);
    emit_schedule(&mut body, "BEZEL_REDRAW_SCHEDULE", &redraw);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("watch_anim.rs");
    std::fs::write(path, body).expect("write watch_anim.rs");
}

fn emit_schedule(body: &mut String, name: &str, vals: &[u32]) {
    body.push_str(&format!("pub static {name}: &[u32] = &[\n"));
    for chunk in vals.chunks(12) {
        body.push_str("    ");
        for v in chunk {
            body.push_str(&format!("{v}, "));
        }
        body.push('\n');
    }
    body.push_str("];\n");
}

/// Monotonic cumulative schedule: frame i → round(ease(i/(N-1)) × total).
fn ease_schedule(frames: usize, total: u32, bez: (f64, f64, f64, f64)) -> Vec<u32> {
    assert!(frames >= 2, "schedule needs at least 2 frames");
    let mut v = Vec::with_capacity(frames);
    let mut prev = 0u32;
    for i in 0..frames {
        let t = i as f64 / (frames - 1) as f64;
        let y = bezier_ease(bez.0, bez.1, bez.2, bez.3, t);
        let c = ((y * total as f64).round() as u32).clamp(prev, total);
        prev = c;
        v.push(c);
    }
    v[0] = 0;
    let last = frames - 1;
    v[last] = total;
    v
}

/// y for a given x on cubic Bezier (0,0)-(p1)-(p2)-(1,1); x solved by bisection
/// (x(u) is monotonic for control x-coords in [0,1]).
fn bezier_ease(p1x: f64, p1y: f64, p2x: f64, p2y: f64, x: f64) -> f64 {
    let eval = |u: f64, a: f64, b: f64| {
        let inv = 1.0 - u;
        3.0 * inv * inv * u * a + 3.0 * inv * u * u * b + u * u * u
    };
    let (mut lo, mut hi) = (0.0f64, 1.0f64);
    for _ in 0..60 {
        let mid = (lo + hi) / 2.0;
        if eval(mid, p1x, p2x) < x {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    eval((lo + hi) / 2.0, p1y, p2y)
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}

fn generate_inter_font() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let font_path = std::path::Path::new("assets/InterDisplay-Bold.ttf");

    let mut body = String::from("/// Auto-generated from InterDisplay-Bold.ttf via fontdue in build.rs\n\n");

    if !font_path.exists() {
        // Stub so builds don't hard-fail before user places the font.
        body.push_str("pub const INTER_FONT_PRESENT: bool = false;\n");
        body.push_str("#[derive(Copy, Clone)]\npub struct Glyph { pub width: u8, pub height: u8, pub advance: u8, pub ymin: i16, pub data: &'static [u8] }\n");
        body.push_str("pub static GLYPHS: [Option<Glyph>; 128] = [None; 128];\n");
        let path = std::path::Path::new(&out_dir).join("inter_font.rs");
        std::fs::write(&path, body).expect("write stub inter_font.rs");
        println!("cargo:warning=assets/InterDisplay-Bold.ttf not found. Place your Inter Display Bold .ttf there. Using stub.");
        println!("cargo:rerun-if-changed=assets/InterDisplay-Bold.ttf");
        return;
    }

    let font_data = std::fs::read(font_path).expect("read Inter font");
    let font = fontdue::Font::from_bytes(font_data.as_slice(), fontdue::FontSettings::default())
        .expect("parse Inter font");

    // Glyph subset derived programmatically so it can never drift from what the
    // date formatter can produce: digits, colon, space, every month name letter,
    // and the ordinal suffixes.
    let mut needed: Vec<char> = "0123456789: ".chars().collect();
    for m in MONTHS {
        needed.extend(m.chars());
    }
    needed.extend(ORDINAL_CHARS.chars());
    needed.sort_unstable();
    needed.dedup();

    body.push_str("pub const INTER_FONT_PRESENT: bool = true;\n");
    body.push_str(&format!(
        "/// Month names (shared with the build-time glyph subset).\npub static MONTH_NAMES: [&str; 12] = {MONTHS:?};\n"
    ));
    body.push_str("#[derive(Copy, Clone)]\npub struct Glyph { pub width: u8, pub height: u8, pub advance: u8, pub ymin: i16, pub data: &'static [u8] }\n");
    body.push_str("pub static GLYPHS: [Option<Glyph>; 128] = [\n");

    for c in 0u8..128 {
        let ch = c as char;
        if needed.contains(&ch) {
            let (metrics, bitmap) = font.rasterize(ch, 72.0); // 2x raster for "scale to gray" AA (see quote in clock.rs)
            let w = metrics.width as u8;
            let h = metrics.height as u8;
            let adv = metrics.advance_width.round() as u8;
            let ymin = metrics.ymin as i16;  // from font metrics - negative for descenders like 'y' to position lower relative to baseline

            if std::env::var("FONT_DEBUG").is_ok()
                && (ch.is_alphabetic() || ch == ':' || ch.is_digit(10))
            {
                println!(
                    "cargo:warning=FONT_METRICS {}: xmin={} ymin={} w={} h={} adv={}",
                    ch, metrics.xmin, metrics.ymin, metrics.width, metrics.height, metrics.advance_width
                );
            }

            // Pack to 1bpp, row-major, bits MSB first in each byte
            let mut packed: Vec<u8> = vec![0; ((w as usize + 7) / 8) * h as usize];
            for y in 0..h as usize {
                for x in 0..w as usize {
                    let val = bitmap[y * w as usize + x];
                    if val > 127 {
                        let byte_idx = y * ((w as usize + 7) / 8) + (x / 8);
                        let bit = 7 - (x % 8);
                        packed[byte_idx] |= 1 << bit;
                    }
                }
            }

            body.push_str(&format!("    Some(Glyph {{ width: {}, height: {}, advance: {}, ymin: {}, data: &[", w, h, adv, ymin));
            for (i, b) in packed.iter().enumerate() {
                if i > 0 { body.push(','); }
                body.push_str(&format!("{}", b));
            }
            body.push_str("] }),\n");
        } else {
            body.push_str("    None,\n");
        }
    }
    body.push_str("];\n");

    let path = std::path::Path::new(&out_dir).join("inter_font.rs");
    std::fs::write(&path, body).expect("write inter_font.rs");
    println!("cargo:rerun-if-changed=assets/InterDisplay-Bold.ttf");
    println!("cargo:rerun-if-changed=build.rs");
}
