fn main() {
    generate_sin_lut();
    generate_inter_font();
    generate_bezel_schedules();
    linker_be_nice();
    // make sure linkall.x is the last linker script (otherwise might cause problems with flip-link)
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

/// 512-entry Q14 sine LUT for src/trig.rs.
fn generate_sin_lut() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let mut body = String::from("pub static SIN_LUT_I16: [i16; 512] = [\n");
    for i in 0..512 {
        let angle = (i as f64 / 512.0) * std::f64::consts::TAU;
        let q14 = ((angle.sin() * 16384.0).round() as i32).clamp(-32768, 32767);
        body.push_str(&format!("{q14}_i16,\n"));
    }
    body.push_str("];\n");
    let path = std::path::Path::new(&out_dir).join("sin_lut.rs");
    std::fs::write(path, body).expect("write sin_lut.rs");
    println!("cargo:rerun-if-changed=build.rs");
}

/// Per-phase cubic Bezier control points, CSS `cubic-bezier(x1, y1, x2, y2)`
/// semantics (P2, docs/09). Peak per-frame delta ≈ avg × curve's max slope —
/// keep max slope ≤ ~1.6 so the worst anim frame stays inside the 91 ms cadence.
///
/// Startup sweep: gentle stately S-curve (validated on hardware — "lovely").
const INITIAL_BEZIER: (f64, f64, f64, f64) = (0.25, 0.1, 0.75, 0.9);
/// Minute change: snappier mid (max slope 1.5), still soft at both ends —
/// reads as a responsive reaction to the tick rather than a slow ornament.
const MINUTE_BEZIER: (f64, f64, f64, f64) = (0.33, 0.0, 0.67, 1.0);

/// Bezel ring animation schedules (docs/09 P0): cumulative arc-center counts per frame.
///
/// Frame-indexed, not wall-clock: the runtime applies `schedule[frame_in_phase]` each
/// frame, so per-frame deltas are bounded by construction (no runtime cap needed) and
/// the ring always reaches the schedule's end state before the phase can exit.
fn generate_bezel_schedules() {
    // Must equal src/clock.rs precompute size: BEZEL_STEPS (36000) × thickness taps (11).
    const TOTAL: u32 = 396_000;
    // The main loop paces frames to exactly this rate (CLOCK_FRAME_US in main.rs),
    // so schedules take precisely their designed wall-clock duration. More fps =
    // more, smaller schedule steps over the same duration = smoother motion;
    // every frame's work must fit 1000/fps ms (worst measured ~45 ms at 20 fps).
    const TARGET_FPS: u64 = 20;
    const INITIAL_MS: u64 = 8_000;
    const UNDRAW_MS: u64 = 3_500;
    const REDRAW_MS: u64 = 3_500;

    let frames = |ms: u64| ((ms * TARGET_FPS + 999) / 1000) as usize;

    let initial = ease_schedule(frames(INITIAL_MS), TOTAL, INITIAL_BEZIER);
    let redraw = ease_schedule(frames(REDRAW_MS), TOTAL, MINUTE_BEZIER);
    // Undraw runs the same S-curve in reverse: TOTAL → 0, slow ends / fast middle.
    let undraw: Vec<u32> = ease_schedule(frames(UNDRAW_MS), TOTAL, MINUTE_BEZIER)
        .iter()
        .map(|&c| TOTAL - c)
        .collect();

    let mut body = String::from(
        "/// Auto-generated by build.rs (generate_bezel_schedules). Do not edit.\n\
         /// Cumulative arc-center counts per frame; index with frame_in_phase.\n",
    );
    body.push_str(&format!(
        "pub const BEZEL_SCHED_TOTAL: u32 = {TOTAL};\n"
    ));
    emit_schedule(&mut body, "BEZEL_INITIAL_SCHEDULE", &initial);
    emit_schedule(&mut body, "BEZEL_UNDRAW_SCHEDULE", &undraw);
    emit_schedule(&mut body, "BEZEL_REDRAW_SCHEDULE", &redraw);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("watch_anim.rs");
    std::fs::write(path, body).expect("write watch_anim.rs");
}

fn emit_schedule(body: &mut String, name: &str, vals: &[u32]) {
    body.push_str(&format!("pub static {name}: &[u32] = &[\n"));
    for chunk in vals.chunks(12) {
        body.push_str("    ");
        for v in chunk {
            body.push_str(&format!("{v}, "));
        }
        body.push('\n');
    }
    body.push_str("];\n");
}

/// Monotonic cumulative schedule: frame i → round(ease(i/(N-1)) × total).
fn ease_schedule(frames: usize, total: u32, bez: (f64, f64, f64, f64)) -> Vec<u32> {
    assert!(frames >= 2, "schedule needs at least 2 frames");
    let mut v = Vec::with_capacity(frames);
    let mut prev = 0u32;
    for i in 0..frames {
        let t = i as f64 / (frames - 1) as f64;
        let y = bezier_ease(bez.0, bez.1, bez.2, bez.3, t);
        let c = ((y * total as f64).round() as u32).clamp(prev, total);
        prev = c;
        v.push(c);
    }
    v[0] = 0;
    let last = frames - 1;
    v[last] = total;
    v
}

/// y for a given x on cubic Bezier (0,0)-(p1)-(p2)-(1,1); x solved by bisection
/// (x(u) is monotonic for control x-coords in [0,1]).
fn bezier_ease(p1x: f64, p1y: f64, p2x: f64, p2y: f64, x: f64) -> f64 {
    let eval = |u: f64, a: f64, b: f64| {
        let inv = 1.0 - u;
        3.0 * inv * inv * u * a + 3.0 * inv * u * u * b + u * u * u
    };
    let (mut lo, mut hi) = (0.0f64, 1.0f64);
    for _ in 0..60 {
        let mid = (lo + hi) / 2.0;
        if eval(mid, p1x, p2x) < x {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    eval((lo + hi) / 2.0, p1y, p2y)
}

fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `defmt` not found - make sure `defmt.x` is added as a linker script and you have included `use defmt_rtt as _;`"
                    );
                    eprintln!();
                }
                "_stack_start" => {
                    eprintln!();
                    eprintln!("💡 Is the linker script `linkall.x` missing?");
                    eprintln!();
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "💡 `esp-radio` has no scheduler enabled. Make sure you have initialized `esp-rtos` or provided an external scheduler."
                    );
                    eprintln!();
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!();
                    eprintln!(
                        "💡 `embedded-test` not found - make sure `embedded-test.x` is added as a linker script for tests"
                    );
                    eprintln!();
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "💡 Did you forget the `esp-alloc` dependency or didn't enable the `compat` feature on it?"
                    );
                    eprintln!();
                }
                _ => (),
            },
            // we don't have anything helpful for "missing-lib" yet
            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe().unwrap().display()
    );
}

fn generate_inter_font() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let font_path = std::path::Path::new("assets/InterDisplay-Bold.ttf");

    let mut body = String::from("/// Auto-generated from InterDisplay-Bold.ttf via fontdue in build.rs\n\n");

    if !font_path.exists() {
        // Stub so builds don't hard-fail before user places the font.
        body.push_str("pub const INTER_FONT_PRESENT: bool = false;\n");
        body.push_str("#[derive(Copy, Clone)]\npub struct Glyph { pub width: u8, pub height: u8, pub advance: u8, pub ymin: i16, pub data: &'static [u8] }\n");
        body.push_str("pub static GLYPHS: [Option<Glyph>; 128] = [None; 128];\n");
        let path = std::path::Path::new(&out_dir).join("inter_font.rs");
        std::fs::write(&path, body).expect("write stub inter_font.rs");
        println!("cargo:warning=assets/InterDisplay-Bold.ttf not found. Place your Inter Display Bold .ttf there. Using stub.");
        println!("cargo:rerun-if-changed=assets/InterDisplay-Bold.ttf");
        return;
    }

    let font_data = std::fs::read(font_path).expect("read Inter font");
    let font = fontdue::Font::from_bytes(font_data.as_slice(), fontdue::FontSettings::default())
        .expect("parse Inter font");

    // Chars we need for time (HH:MM) and date "July 7th 2026"
    let needed: Vec<char> = "0123456789:July 7th 2026".chars().collect();

    body.push_str("pub const INTER_FONT_PRESENT: bool = true;\n");
    body.push_str("#[derive(Copy, Clone)]\npub struct Glyph { pub width: u8, pub height: u8, pub advance: u8, pub ymin: i16, pub data: &'static [u8] }\n");
    body.push_str("pub static GLYPHS: [Option<Glyph>; 128] = [\n");

    for c in 0u8..128 {
        let ch = c as char;
        if needed.contains(&ch) {
            let (metrics, bitmap) = font.rasterize(ch, 72.0); // 2x raster for "scale to gray" AA (see quote in clock.rs)
            let w = metrics.width as u8;
            let h = metrics.height as u8;
            let adv = metrics.advance_width.round() as u8;
            let ymin = metrics.ymin as i16;  // from font metrics - negative for descenders like 'y' to position lower relative to baseline

            if std::env::var("FONT_DEBUG").is_ok()
                && (ch.is_alphabetic() || ch == ':' || ch.is_digit(10))
            {
                println!(
                    "cargo:warning=FONT_METRICS {}: xmin={} ymin={} w={} h={} adv={}",
                    ch, metrics.xmin, metrics.ymin, metrics.width, metrics.height, metrics.advance_width
                );
            }

            // Pack to 1bpp, row-major, bits MSB first in each byte
            let mut packed: Vec<u8> = vec![0; ((w as usize + 7) / 8) * h as usize];
            for y in 0..h as usize {
                for x in 0..w as usize {
                    let val = bitmap[y * w as usize + x];
                    if val > 127 {
                        let byte_idx = y * ((w as usize + 7) / 8) + (x / 8);
                        let bit = 7 - (x % 8);
                        packed[byte_idx] |= 1 << bit;
                    }
                }
            }

            body.push_str(&format!("    Some(Glyph {{ width: {}, height: {}, advance: {}, ymin: {}, data: &[", w, h, adv, ymin));
            for (i, b) in packed.iter().enumerate() {
                if i > 0 { body.push(','); }
                body.push_str(&format!("{}", b));
            }
            body.push_str("] }),\n");
        } else {
            body.push_str("    None,\n");
        }
    }
    body.push_str("];\n");

    let path = std::path::Path::new(&out_dir).join("inter_font.rs");
    std::fs::write(&path, body).expect("write inter_font.rs");
    println!("cargo:rerun-if-changed=assets/InterDisplay-Bold.ttf");
    println!("cargo:rerun-if-changed=build.rs");
}
