//! Unlocked scene: fullscreen Spike image (docs/ROADMAP.md M3).
//!
//! The asset is display-ready RGB565-BE generated by build.rs (crop → 466×466
//! → Bayer dither) and memory-mapped from flash — showing it is one memcpy.
//! The round clip is the physical panel.

use crate::display::watch_fb::WatchFb;

/// 466×466 RGB565 big-endian, generated from assets/Spike.jpg by build.rs.
pub static SPIKE_RGB565: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/spike_rgb565.bin"));

/// Paint the full image onto the canvas (marks the whole frame dirty).
pub fn draw(wfb: &mut WatchFb) {
    let buf = wfb.buf_mut();
    let n = buf.len().min(SPIKE_RGB565.len());
    buf[..n].copy_from_slice(&SPIKE_RGB565[..n]);
    let (w, h) = (466i32, 466i32);
    wfb.mark_rect(0, 0, w - 1, h - 1);
}
